version: "3.7"

services:
  tezland-metadata-processing:
    container_name: tezland-metadata-processing
    image: tezland/metadata-processing:$TAG
    build:
      context: .
      dockerfile: Dockerfile
    # in theory depends on db-dipdup, but also not really
    #depends_on:
    #  db-dipdup:
    #    condition: service_healthy
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}

#volumes:
#  db-dipdup:

networks:
  default:
    name: tz1and_prod